package edu.luisguzman.reto7_2.ui;

public class Idiomas {
    public String MENU;
    public String SELECCION_SUMA;
    public String SELECCION_RESTA;
    public String SELECCION_MULTIPLICACION;
    public String SELECCION_DIVISION;
    public String SELECCION_MODULO;
    public String SELECCION_POTENCIA;
    public String SELECCION_RAIZ;
    public String SELECCION_LOGARITMO;
    public String SELECCION_SALIR;
    public String INGRESE_PRIMERNUM;
    public String INGRESE_SEGUNDONUM;
    public String EL_RESULTADO;
    public String INGRESE_DIVIDENDO;
    public String INGRESE_DIVISOR;
    public String INGRESE_MULTIPLICADOR;
    public String INGRESE_MULTIPLICADO;
    public String INGRESE_LA_BASE;
    public String INGRESE_EXPONENTE;
    public String Despedida;
    public String ES;
    public String INGRESE_LOGARITMO;
    public String LOGARITMO_NEGATIVO;
    public String INGRESE_RAIZ;
    public String RAIZ_NEGATIVA;
    public String RAIZ_CUADRADA;
    public String DEFAULT;
    public String OTRA_OPERACION;
    public String Error_DIVISION;
    public String ERROR_LOGARITMO;
    public String LOGARITMO_NATURAL;
    public String ES_ES;
    public String COCIENTE_ES;
    public String RESTO_ES;
    protected String SI;
    protected String NO;
}
